id = "blank-theme"
name = "Blank Theme"
version = "1.0.4"
schema_version = 1
authors = ["Aryan Kathawale <kathawalearyan9@gmail.com>"]
description = "An Elegant and Minimalist Theme for Zed."
repository = "https://github.com/kiritocode1/Blank-Theme"
